@startuml
class SudokuGeneratorTransformation {
    + Sudoku generateSudoku(Difficulty difficulty)
}

class SudokuGeneratorBacktracking {
    + Sudoku generateSudoku(Difficulty difficulty)
}

@enduml
