@startuml
class SudokuTransformator {
   - Sudoku fillSudokuWithDigits(List<Integer> unusedDigit)
   - List<Integer> addShuffledDigits()
   - void transform()
   - void removeFields(Difficulty dif)
   - void removeNumberOfCells(int amountOfCellsToRemove)
   - boolean isSudokuSolvable(int[][] sudokuField, int row, int col)
   - void mirrorVertical()
   - ...()
}
@enduml
