@startuml
class SudokuValidatorService {
   + boolean isSudokuFullyFilled(int[][] gameField)
}

class PlayDialogService {
   + void startGame()
}

PlayDialogService --> SudokuValidatorService
@enduml
