@startuml
class User {
  - String userName
  - String password
  + String getUserName()
  + String getPassword()
}

interface UserPort {
   void saveUser(User user)
   String getPassword(String userName)
   List<String> getAllUserNames()
}

class UserAdapter {
   + void saveUser(User user)
   + String getPassword(String userName)
   + List<String> getAllUserNames()
}

UserAdapter--> "Inheritance" UserPort
UserAdapter-->User
UserPort-->User
@enduml