@startuml
'https://plantuml.com/class-diagram

enum LeaderboardType {
COMPLETE
SOLVINGTIME
DIFFICULTY_EASY
DIFFICULTY_MEDIUM
DIFFICULTY_HARD
}

class LeaderboardDialogService {
- LeaderboardType leaderboardType
--
- loadAndDisplayCorrectLeaderboard(int userInput)
- displayLeaderboard(Leaderboard leaderboard)
}

LeaderboardType <-- LeaderboardDialogService

@enduml