@startuml
class SudokoBuilder {
  - String id
  - SudokuArray gameField
  - SudokuArray initialGameField
  - SudokuArray solvedGameField
  - Difficulty difficulty
  - SudokuBuilder(SudokuArray sudokuArray)
  - SudokuBuilder(SudokuSize size)
  + {static} SudokuBuilder withGameField(SudokuSize size)
  + {static} SudokuBuilder withSize(SudokuSize size)
  + SudokuBuilder withId(String id)
  + SudokuBuilder withInitialGameField(SudokuArray initialGameField)
  + SudokuBuilder withSolvedGameField(SudokuArray solvedGameField)
  + SudokuBuilder withDifficulty(Difficulty difficulty)
  + Sudoku build()
}

class Sudoku {
  - String id
  - SudokuArray gameField
  - SudokuArray initialGameField
  - SudokuArray solvedGameField
  - SudokuChange lastChange
  - Difficulty difficulty
  + Sudoku(String id, SudokuArray gameField, SudokuArray initialGameField, SudokuArray solvedGameField, Difficulty difficulty)
  + SudokuArray getGameField()
  + SudokuArray getInitialGameField()
  + SudokuArray getSolvedGameField()
  + Difficulty getDifficulty()
  + SudokuChange getLastChange()
  + String getId()
  + void setInitialGameField(initialGameField)
  + void setSolvedGameField(initialGameField)
  + boolean setField(row, col, val)
}

SudokoBuilder -->"erzeugt"Sudoku
@enduml
