@startuml
class DependencyFactory {
  - {static} DependencyFactory instance
  - List<Object> dependencies
  - DependencyFactory()
  + {static} DependencyFactory getInstance()
  + void registerDependency(Object o)
  + T getDependency(Class<T> type)
}
DependencyFactory --> "instance" DependencyFactory: <<singleton>>
@enduml
